name: Rust

on:
  push:
    # Run jobs when commits are pushed to
    # master or release-like branches:
    branches:
      - master
      - release*
  pull_request:
    # Run jobs for any external PR that wants
    # to merge to master, too:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: check
          args: --all-targets --all-features

  fmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Cargo fmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

  docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Check internal documentation links
        run: RUSTDOCFLAGS="--deny broken_intra_doc_links" cargo doc --verbose --workspace --no-deps --document-private-items

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Cargo build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --workspace

      - name: Cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test

